# Generated by Django 5.0.3 on 2026-01-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
