# Generated by Django 5.0.3 on 2026-01-26 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_topping_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuTopping',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
