# Generated by Django 5.0.3 on 2026-03-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_delete_menutopping_delete_topping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True)),
                ('background_color', models.CharField(default='#ffdb58', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
