# Generated by Django 5.0.3 on 2026-03-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class name like fa-hamburger', max_length=50, null=True),
        ),
    ]
