# Generated by Django 5.0.3 on 2026-03-12 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_promotion'),
        ('toppings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='menu.category'),
        ),
        migrations.AddField(
            model_name='topping',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
