# Generated by Django 5.0.3 on 2026-01-26 22:26

from django.db import migrations


def fix_schema_forward(apps, schema_editor):
    """Fix the OrderItemTopping table schema by dropping topping_id and adding topping_name"""
    with schema_editor.connection.cursor() as cursor:
        vendor = schema_editor.connection.vendor
        if vendor == 'mysql':
            cursor.execute("ALTER TABLE orders_orderitemtopping DROP FOREIGN KEY orders_orderitemtopp_topping_id_4373495a_fk_toppings_")
            cursor.execute("ALTER TABLE orders_orderitemtopping DROP INDEX orders_orderitemtopp_topping_id_4373495a_fk_toppings_")
        else:
            # PostgreSQL: find and drop the FK constraint dynamically
            cursor.execute("""
                SELECT constraint_name FROM information_schema.table_constraints
                WHERE table_name = 'orders_orderitemtopping' AND constraint_type = 'FOREIGN KEY'
                AND constraint_name LIKE '%topping_id%'
            """)
            for row in cursor.fetchall():
                cursor.execute(f"ALTER TABLE orders_orderitemtopping DROP CONSTRAINT {row[0]}")
            # Drop any index on topping_id
            cursor.execute("""
                SELECT indexname FROM pg_indexes
                WHERE tablename = 'orders_orderitemtopping' AND indexname LIKE '%topping_id%'
            """)
            for row in cursor.fetchall():
                cursor.execute(f"DROP INDEX IF EXISTS {row[0]}")
        # Drop the topping_id column
        cursor.execute("ALTER TABLE orders_orderitemtopping DROP COLUMN topping_id")
        # Add the topping_name column
        cursor.execute("ALTER TABLE orders_orderitemtopping ADD COLUMN topping_name VARCHAR(100) NOT NULL DEFAULT ''")


def fix_schema_backward(apps, schema_editor):
    """Reverse the schema changes"""
    with schema_editor.connection.cursor() as cursor:
        # Drop topping_name and restore topping_id
        cursor.execute("ALTER TABLE orders_orderitemtopping DROP COLUMN topping_name")
        cursor.execute("ALTER TABLE orders_orderitemtopping ADD COLUMN topping_id BIGINT NOT NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fix_schema_forward, fix_schema_backward),
    ]
