# Generated by Django 5.0.3 on 2026-01-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delivery_bike_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='bike_id',
            new_name='bike',
        ),
    ]
