# Generated by Django 5.0.3 on 2026-01-23 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
        ('users', '0003_rename_bike_id_delivery_bike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bike.bike'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
